services:
  - type: web
    name: atm-django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ATM001.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ATM001.settings
