# Generated by Django 5.1.2 on 2025-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('acc', models.CharField(max_length=12)),
                ('ifsc', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
